### ISSUE TITLE
[Feature Requset] Hunting Log Tracking

### ISSUE THREAD

**Issue by eaganlai** [SheepGoMeh/HuntBuddy#11]
How about including Hunting Log in the plugin as well?

It would be great if it can have "sort by job" and "sort by zone" like how Tourist handled zone and number sorting!

**Comment by raitono** [comment]
I was looking for something for exactly this. The only other plugin that seemed to do it had many locations that were completely wrong so ended up being more frustrating than without it.

**Comment by PrincessRTFM** [comment]
Sorry to disappoint, but this is very unlikely to happen. The locations of all mobs are hand-coded, which means that every single hunt log mob would need to be found somewhere consistent and written into the project, along with the code to get unfinished targets from the hunting log. That'd be a lot of work, and you only ever do the hunting log once (per character), which means a lot of work for comparatively little payoff. On the other hand, the hunt is doable literally every single day, and with varying targets, which makes this a much more convenient option than looking up maps online for every mob.

Maybe someday in the future, but Sheep and I would like to go through the existing code first to see about cleaning some things up. In the meantime, if you haven't tried [Hunty](https://github.com/Infiziert90/Hunty) yet, you could look into that. If the locations are wrong, you should be able to report them to the dev.
