### ISSUE TITLE
Map Markers for ARR Hunts

### ISSUE THREAD

**Issue by TeleTabs** [SheepGoMeh/HuntBuddy#13]
PLEASE!

**Comment by xandris** [comment]
Marked completed, but is this actually just rejected?

**Comment by PrincessRTFM** [comment]
As stated by the plugin owner in issue #7, ARR mobs will not be added. The problem that HB aims to solve is that HW+ hunts aren't organised, allowing the same mob to show up in more than one hunt bill. ARR hunts don't do this. There's only a single hunt bill for ARR dailies.

Furthermore, a number of those mobs are FATE-exclusive, which means that either a total overhaul/rewrite would be needed to allow indicating this, or the location would lead you to a place where the mobs may well not exist at the time.
