### ISSUE TITLE
Feature Request: /command to "Place Marker on Map" for nearest/next Hunt.

### ISSUE THREAD

**Issue by Willshaper** [SheepGoMeh/HuntBuddy#14]
Hey.

I'd like to request a /command being added for the "Place Marker on Map" function, either the nearest hunt, and if that's not possible, just the next on the list. Maybe Cycling them on each usage?

Reason for this is that I play with a Controller, so each time I deal with a target, I have to switch back to Mouse/KB to pick the next one.

**Comment by PrincessRTFM** [comment]
Done, just waiting on #17 to be merged
