### ISSUE TITLE
Feature Request: Multiple markers on map

### ISSUE THREAD

**Issue by Noshei** [SheepGoMeh/HuntBuddy#16]
When you have multiple hunts in the same zone, it would be nice if you could mark all of them at the same time, instead of having to switch between each one to see where they all are.

**Comment by PrincessRTFM** [comment]
I'll take a look into this since I know that area circles can seemingly coexist, but the method used to show things on the minimap only supports showing one marker. In the meantime, you can try using `/phb next` with the latest update, to get a marker to the _closest_ target.

**Comment by electr0sheep** [comment]
Last patch (Dalamud and game) it seemed like the max gathering markers was 5 at a time. I implemented a way to cycle through the possible locations, but it kinda sucked. When I get some time, I'll have to see if I can't clean up the code and submit a PR for this.

**Comment by PrincessRTFM** [comment]
If you're talking about the B-rank ones, [we probably won't be adding them regardless](https://github.com/SheepGoMeh/HuntBuddy/issues/19), since as the linked issue states, that's not the point of HB. Unless Sheep has changed their mind, I wouldn't expect it to be implemented.
