### ISSUE TITLE
Map Markers for Heavensward Hunts

### ISSUE THREAD

**Issue by Ultameciia** [SheepGoMeh/HuntBuddy#2]
Is there future plans for the addition of these map markers? It'd make my quest for endless free teleports much easier. If need be I wouldn't mind getting x,y coords for them.

**Comment by DiggityMan420** [comment]
I would like to see then for storm and ARR too

**Comment by skifty** [comment]
I really hope locations for older expansions and ARR will eventually come to the plugin. I thought mine was just bugged.

**Comment by Riiskyy** [comment]
I'm also hoping for this for older expansions. At first i thought it was a bug with the plugin when i couldn't see them for ARR/HW/SB

**Comment by DiggityMan420** [comment]
Why was this closed???

**Comment by Riiskyy** [comment]
> Why was this closed???

It was closed because it was updated and merged in to the plugin. You can see it in the commit message
