### ISSUE TITLE
Region tab collapses after finishing one type of enemy.

### ISSUE THREAD

**Issue by Zephylius** [SheepGoMeh/HuntBuddy#3]
Is it possible to prevent the regional menu showing the enemies from closing when you finish up one mark in that region? For example, if you have two marks in Thavnair, and you kill one of them, it collapses the thavnair menu so you have to manually reopen it. Also, is there any plans to add support for ARR/HW/SB? I love this plugin and thank you for your time!

**Comment by karpik123** [comment]
After testing the plugin for two days, I concur - collapsing a region after completing mob type is on the annoying side!
