### ISSUE TITLE
Teleporter&mark on map

### ISSUE THREAD

**Issue by warknight1211** [SheepGoMeh/HuntBuddy#35]
version I am using：v1.0.5.2

I saw screenshots of the interface of the previous version on the Internet, and saw buttons for teleportation and marking on the map, but the version I am using now does not have these two functions. 
Have these two functions been removed? Or am I missing some settings?
I'm pretty sure I have Teleport installed and it works fine with gatherbuddy.
If these two functions are removed, is there an alternative way to implement these two functions?

**Comment by PrincessRTFM** [comment]
Are you looking at a _daily_ mark or a _weekly_ mark? Because weekly marks do not have those functions, and never have.

**Comment by warknight1211** [comment]
There are 2 links here, one in Chinese and one in Japanese. In the pictures in the links, you can see the teleport and map mark buttons.

https://toramemoblog.com/xiv-huntbuddy

https://www.bilibili.com/read/cv16626318/

**Comment by PrincessRTFM** [comment]
Neither of these is in English, which is the language spoken by both developers. Regardless, that feature _does_ exist, yes - for _daily_ marks. Not for _weekly_ marks. Weekly marks do not have either of those features. Daily marks have _both_ of them.
