### ISSUE TITLE
Don't have the same interface as my son for daily hunts

### ISSUE THREAD

**Issue by graphicschyk** [SheepGoMeh/HuntBuddy#43]
Hi, my son suggested I install this today, but we can't figure out why his screen has icons and buttons that he can click to go to the hunt and he can see them on the map, but all I have is the attached. We checked settings and both are the same. 
![huntbuddy1](https://github.com/SheepGoMeh/HuntBuddy/assets/175161059/543d5d13-849a-4e5e-98a0-3f89af1e6871)

**Comment by graphicschyk** [comment]
My settings 
![image](https://github.com/SheepGoMeh/HuntBuddy/assets/175161059/80189552-bacf-4bd2-8787-22532a9b000f)
His settings
![image](https://github.com/SheepGoMeh/HuntBuddy/assets/175161059/ebc5e69c-67a7-424f-a100-18aefbd5bc34)

**Comment by PrincessRTFM** [comment]
Gatling is a B-rank. B-ranks do not have locations provided by the plugin, because they can spawn in multiple locations, often covering at least half the map zone. Acquire daily hunt bills and their targets will have the buttons.

**Comment by graphicschyk** [comment]
I will try again tomorrow, but I did have the daily hunts. I took the daily and weekly and even after I deleted the weekly out of my inventory I still didn't get the buttons.

**Comment by graphicschyk** [comment]
Here, today I took the daily hunt and here is what my screen looks like:
![image](https://github.com/SheepGoMeh/HuntBuddy/assets/175161059/f5d8c3f9-8dfe-4b25-877b-716751d97fb1)
and this is the map, the only indication I can see on the map is the little icons in the upper left next to each location name 
![image](https://github.com/SheepGoMeh/HuntBuddy/assets/175161059/75442d2f-bd91-40a7-9fc8-4db5cb9bed0e)
