### ISSUE TITLE
[Suggestion] Toggle option for auto-open map

### ISSUE THREAD

**Issue by cc12138030** [SheepGoMeh/HuntBuddy#5]
An option to toggle whether the clickable magnifying glass on the "hunts in current area" window will open the map. 

Basically just an option that allows you to choose whether or not to open the map when clicking the buttons that I highlighted in the screenshot, but have it still place the flag/waypoint. Since the "hunts in current area" panel only opens when you're in the right zone, I just need the waypoint marker in order fly in the right direction and don't need the whole map to open.

![HuntBuddy](https://user-images.githubusercontent.com/43885259/150849861-2c77766b-eb2e-4c28-9ffa-94c72ba9f47b.jpg)

This is just a small QoL change, and I'm not even sure if this is something else anyone would want. Just thought I'd throw this out there. Let me know if you need any further clarification.

**Comment by DiggityMan420** [comment]
maybe like Right Click open map and left click Don't I could see that being useful
