### ISSUE TITLE
Add Ignore ESC key option

### ISSUE THREAD

**Issue by GlassAlice** [SheepGoMeh/HuntBuddy#51]
As the title says i just found this plug in and enjoy it alot but i keep accidently turning off hud when i close other windows hitting the escape key. 

Iv seen other plug ins use a options that simply says "ignore esc key"  and like you basically have to click into the plug in so its in focus for esc to close it.

Im brand new to git hub this is my first time trying to leave feedback im sorry if i did this the incorrect way.

**Comment by SheepGoMeh** [comment]
Thank you for your issue!
An option will be added in the next version of the plugin 😊
