### ISSUE TITLE
[Suggestion] Frame resize persist between sessions.

### ISSUE THREAD

**Issue by TotalHamman** [SheepGoMeh/HuntBuddy#6]
HuntBuddy Frame resize does not persist between sessions (game relaunches).  It would save me the inconvenience of having to resize the frame each time I launch the game.

**Comment by PrincessRTFM** [comment]
Is this still an issue? If so, please elaborate: what do you mean _specifically_ by "frame" here? The main plugin window?

**Comment by PrincessRTFM** [comment]
Having discovered that the plugin window doesn't maintain size changes between game launches, I think I know what you mean. I'll take a look into it.

**Comment by PrincessRTFM** [comment]
There's been no word on this, but a feedback submission was recently received indicating that it's still an issue. When I have the time, I'm going to see about rewriting the UI to use dalamud's windowing system.
