### ISSUE TITLE
[Suggestion] ARR Locations

### ISSUE THREAD

**Issue by DiggityMan420** [SheepGoMeh/HuntBuddy#7]
I see you have added Stormblood and Heavenward any plans on adding ARR too?

**Comment by DiggityMan420** [comment]
Also The Dravanian Hinterlands the closest tele is Idyllshire so the button don't work don't know if u wan to fix it to send you too idy. [Pic](https://imgshare.io/image/rbflBn)

**Comment by mkolassa** [comment]
Is there a technical reason for not wanting to add them?  If not, I don't mind putting in the work to add the dictionary items and submitting a pull request if you would be agreeable to it.
