### ISSUE TITLE
Updated Locations

### ISSUE THREAD

**Issue by DiggityMan420** [SheepGoMeh/HuntBuddy#8]
I found some locations we're sorta off or some we're really off so if you want these are updated locations to what I found

Vouivre = The Churning Mists ( 38.0 , 17.7 )
Gazelle Hawk = The Fringes ( 11.6  , 12.0 )
Ancient Lizard = Amh Araeng ( 29.4  , 25.4 )

**Comment by Fotosha** [comment]
Ringtail = Outer La Noscea ( 15.2  , 12.5 )
